#undef TAPPING_TERM
#define TAPPING_TERM 175

#define ONESHOT_TAP_TOGGLE 2

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "bm7JD/zL4mQr"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

